import * as cheerio from 'cheerio';
const UA='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123 Safari/537.36';
async function fetchHTML(url){const res=await fetch(url,{headers:{'User-Agent':UA}});if(!res.ok)throw new Error('HTTP '+res.status+' on '+url);return await res.text()}
function money(text=''){let m=text.match(/([$€£])\s?(\d[\d,]*(?:\.\d{1,2})?)/);if(m)return{price:m[2],currency:({'$':'USD','€':'EUR','£':'GBP'})[m[1]]||''};m=text.match(/(\d[\d,]*(?:\.\d{1,2})?)\s?(USD|EUR|GBP)/i);if(m)return{price:m[1],currency:m[2].toUpperCase()};return{price:'',currency:''}}
function pn(s=''){const m=String(s).match(/[A-Z0-9-]{5,}/i);return m?m[0].toUpperCase():''}

export async function fromRepairClinic(q){const url=`https://www.repairclinic.com/Search?query=${encodeURIComponent(q)}`;const html=await fetchHTML(url);const $=cheerio.load(html);const items=[];$('[data-qa="product-tile"], .product-tile, .search-results__grid-item').each((_,el)=>{const name=$(el).text().trim().replace(/\s+/g,' ');const a=$(el).find('a[href]').first();const href=a.attr('href')||'';const link=href.startsWith('/')?'https://www.repairclinic.com'+href:href;const priceText=$(el).find('.price,[data-qa="product-price"]').text();const {price,currency}=money(priceText);const img=$(el).find('img').attr('src')||'';items.push({supplier:'RepairClinic',name,url:link,image:img,price,currency,part_number:pn(name)})});return items}

export async function fromAppliancePartsPros(q){const url=`https://www.appliancepartspros.com/search.aspx?model=${encodeURIComponent(q)}`;const html=await fetchHTML(url);const $=cheerio.load(html);const items=[];$('.product, .plp-product, .search-results .product-list-item').each((_,el)=>{const titleEl=$(el).find('.product-title, h2 a, a[title]').first();const name=titleEl.text().trim()||$(el).text().trim();let link=titleEl.attr('href')||'';if(link&&link.startsWith('/'))link='https://www.appliancepartspros.com'+link;const priceText=$(el).text();const {price,currency}=money(priceText);const img=$(el).find('img').attr('src')||'';items.push({supplier:'AppliancePartsPros',name,url:link,image:img,price,currency,part_number:pn(name)})});return items}

export async function fromPartSelect(q){const url=`https://www.partselect.com/AdvancedSearch.aspx?SearchTerm=${encodeURIComponent(q)}`;const html=await fetchHTML(url);const $=cheerio.load(html);const items=[];$('.product-list li, .product-list__item, .ps-product-tile').each((_,el)=>{const name=$(el).text().trim().replace(/\s+/g,' ');const a=$(el).find('a[href]').first();let link=a.attr('href')||'';if(link&&link.startsWith('/'))link='https://www.partselect.com'+link;const img=$(el).find('img').attr('src')||'';const {price,currency}=money($(el).text());items.push({supplier:'PartSelect',name,url:link,image:img,price,currency,part_number:pn(name)})});return items}

export async function fromSears(q){const url=`https://www.searspartsdirect.com/search?q=${encodeURIComponent(q)}`;const html=await fetchHTML(url);const $=cheerio.load(html);const items=[];$('.card, .product-card, [data-component="product-card"], a[href*="/product/"], a[href*="/part/"]').each((_,el)=>{const name=$(el).text().trim().replace(/\s+/g,' ');const a=$(el).attribs&&$(el).attribs.href?$(el):$(el).find('a[href]').first();let link=(a.attr('href')||'').trim();if(!link)return;if(link.startsWith('/'))link='https://www.searspartsdirect.com'+link;const img=$(el).find('img').attr('src')||'';const {price,currency}=money($(el).text());items.push({supplier:'SearsPartsDirect',name,url:link,image:img,price,currency,part_number:pn(name)})});return items}

//export async function fromEbayAPI(q){const token=process.env.EBAY_OAUTH;if(!token)return[];const u=new URL('https://api.ebay.com/buy/browse/v1/item_summary/search');u.searchParams.set('q',q);u.searchParams.set('limit','20');const res=await fetch(u,{headers:{Authorization:`Bearer ${token}`,'X-EBAY-C-MARKETPLACE-ID':'EBAY_US'}});if(!res.ok)return[];const data=await res.json();return (data.itemSummaries||[]).map(it=>({supplier:'eBay',name:it.title||'',url:it.itemWebUrl||'',image:(it.image&&it.image.imageUrl)||'',price:it.price?.value||'',currency:it.price?.currency||'',part_number:pn(it.title||'')}))}
//export async function fromAmazonAPI(q){return[]}
